spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/db_thinker_auth
    username: root
    password: root
    initialization-mode: always
    data: classpath:data.sql
  redis:
    host: 192.168.50.80
server:
  port: 7070

